Vz mini pol assay
ericmjl/protein-systematic-characterization pull request #50
Opened 2016-11-17 17:33 UTC by Starnite

2016-11-17 18:48 UTC, ericmjl requested changes

2016-11-17 18:48 UTC, ericmjl commented on experiments/20161104-pol-assay-high-throughput/20161117-primer-design.md
> +Reverse: TTTCACAAATAAAGCATTTT
Can you annotate the predicted melting temperature of the primer? It should ideally be roughly in the 55-65ºC range. If not, extend the primer until you hit that range.

2016-11-17 18:48 UTC, ericmjl commented on goals/Nov-16.md
> +## Goals for Nov 17 - Nov 22
I think you should remove this file from the branch. It's already present in a separate branch.

2016-11-18 01:58 UTC, ericmjl commented on experiments/20161104-pol-assay-high-throughput/20161117-primer-design.md
> +Reverse: CATCACAAATTTCACAAATAAAGCATTTT (29-mer, Tm = 55C, %GC = 24)
Both primers are checked, they look good. I will order them in.

2016-11-20 21:16 UTC, ericmjl commented
@Starnite: looks like there's an issue here - data compilation code in this branch is conflicting with data compilation code from other branch. Which one should be the one that is final? I suspect it's the other branch; you might have to revert changes from 6cdef56 and discard the changed files in this branch.

2016-11-20 21:26 UTC, Starnite commented
Sorry, I was having issues with committing new changes on the mini-pol-assay branch. The final version should be the vz-data-analysis branch.

From: Eric Ma [mailto:notifications@github.com]
Sent: Sunday, November 20, 2016 4:17 PM
To: ericmjl/protein-systematic-characterization <protein-systematic-characterization@noreply.github.com>
Cc: Jiwei Zhong <vivzhong@mit.edu>; Mention <mention@noreply.github.com>
Subject: Re: [ericmjl/protein-systematic-characterization] Vz mini pol assay (#50)


@Starnite<https://github.com/Starnite>: looks like there's an issue here - data compilation code in this branch is conflicting with data compilation code from other branch. Which one should be the one that is final? I suspect it's the other branch; you might have to revert changes from 6cdef56<https://github.com/ericmjl/protein-systematic-characterization/commit/6cdef562e08f7a6e599dadaa50a2a48be1cd5bd4> and discard the changed files in this branch.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ericmjl/protein-systematic-characterization/pull/50#issuecomment-261806392>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ANrO2SxyywEv19UVzWk9fJzDsnliWx9Wks5rALi4gaJpZM4K1lyd>.

2016-11-21 15:09 UTC, ericmjl commented
@Starnite in that case, be sure to do the following:

(1) In GitHub desktop, revert the change 6cdef56.
(2) After that, discard changes to the four conflicting files above.
(3) Push.

2016-11-21 21:54 UTC, ericmjl approved these changes

2016-11-21 21:56 UTC, merged