Vz mini pol assay cont
ericmjl/protein-systematic-characterization pull request #58
Opened 2016-11-23 01:18 UTC by Starnite

2016-11-23 01:43 UTC, ericmjl requested changes
Overall great work! Would like to know a bit more about thought process.

2016-11-23 01:43 UTC, ericmjl commented on experiments/20161104-pol-assay-high-throughput/20161117-second-run.md
> +- Mix cells in DMEM before seeding, and mix thoroughly in Falcon tube and in trough
Great stuff picking up these tips! Can you ensure they are reflected in the protocol as well?

2016-11-23 01:43 UTC, ericmjl commented on experiments/20161104-pol-assay-high-throughput/20161117-second-run.md
> +- Accidentally left luciferase supernatant samples in 25C for 15 hours, but signal was still picked up during luminescence scanning. Only the first two rows of samples were tested.
Can you add in an annotation as to why only the first two rows were tested? If it was because of "not enough reagent", that's good to know as well.

2016-11-23 01:45 UTC, ericmjl requested changes

2016-11-23 01:45 UTC, ericmjl commented on experiments/20161104-pol-assay-high-throughput/20161117-second-run.md
> +- The first sample of Vic 1:1 dilution does not appear to contain any cells.
Make sure that you note later on whether this is a reason for excluding a sample - and yes, it can be a reason for doing so.

2016-12-05 22:43 UTC, Starnite commented
Sequencing submitted!

2016-12-05 22:57 UTC, ericmjl commented
Cool stuff, make sure it's recorded!

2017-02-01 14:23 UTC, ericmjl approved these changes

2017-02-01 14:24 UTC, merged

2017-02-01 14:24 UTC, ericmjl commented
@Starnite: merging in!